# Generated by Django 3.2.3 on 2021-06-15 21:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmtree', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tree',
            name='id',
            field=models.SlugField(max_length=25, primary_key=True, serialize=False, verbose_name='Slug'),
        ),
    ]
