# Generated by Django 3.2.3 on 2021-06-30 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmtree', '0004_auto_20210626_1532'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254, verbose_name='E-Mail'),
        ),
    ]
