# Generated by Django 3.2.3 on 2021-06-30 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mlmtree', '0005_person_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='tree',
            name='urlpattern',
            field=models.URLField(blank=True, default='', help_text='Platzhalter: ${EMAIL}, ${USERID}', verbose_name='URL-Vorlage'),
        ),
    ]
